/** API endpoint constants matching the FastAPI router prefixes. */
export const API = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
  },
  ADMIN: {
    USERS: "/admin/users",
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    USER_VERIFICATION: (id: string) => `/admin/users/${id}/verification`,
  },
  INTAKE: {
    TRANSLATE: "/intake/translate",
    RFQS: "/intake/rfqs",
    RFQ: (id: string) => `/intake/rfqs/${id}`,
    RFQ_BATCH: "/intake/rfqs/batch",
    RFQ_STATUS: (id: string) => `/intake/rfqs/${id}/status`,
    RFQ_PRODUCTS: (id: string) => `/intake/rfqs/${id}/products`,
    RFQ_PRODUCTS_BATCH: "/intake/rfqs/products/batch",
    RFQ_MATCH: (id: string) => `/intake/rfqs/${id}/match`,
    RFQ_MATCHED: "/intake/rfqs/matched",
    RFQ_PUBLIC: "/intake/rfqs/public",
    MATCH_CLAIM: (id: string) => `/intake/matches/${id}/claim`,
  },
  DOCUMENTS: {
    UPLOAD: "/documents/upload",
    LIST: (rfqId: string) => `/documents/rfq/${rfqId}`,
    DOCUMENT: (id: string) => `/documents/${id}`,
    PROCESS: (id: string) => `/documents/${id}/process`,
    STATUS: (id: string) => `/documents/${id}/status`,
    ITEMS: (id: string) => `/documents/${id}/items`,
  },
  PRICING: {
    RULES: "/pricing/rules",
    RULE: (id: string) => `/pricing/rules/${id}`,
    RULE_HISTORY: (id: string) => `/pricing/rules/${id}/history`,
    HS_CODES: "/pricing/hs-codes",
    HS_CODE: (code: string) => `/pricing/hs-codes/${code}`,
    CALCULATE: "/pricing/calculate",
    ESTIMATE: "/pricing/estimate",
    REFRESH_RATES: "/pricing/exchange-rates/refresh",
  },
  QUOTES: {
    LIST: "/quotes",
    CREATE: "/quotes",
    QUOTE: (id: string) => `/quotes/${id}`,
    STATUS: (id: string) => `/quotes/${id}/status`,
    GENERATE: "/quotes/generate",
    PDF: (id: string) => `/quotes/${id}/pdf`,
    FINALIZE: (id: string) => `/quotes/${id}/finalize`,
    ACCEPT: (id: string) => `/quotes/${id}/accept`,
    REJECT: (id: string) => `/quotes/${id}/reject`,
    TRACKING: (id: string) => `/quotes/${id}/tracking`,
  },
  CATALOG: {
    PRODUCTS: "/catalog/products",
    PENDING: "/catalog/products/pending",
    REVIEW: (id: string) => `/catalog/products/${id}/review`,
    ADMIN: "/catalog/products/admin",
  },
} as const;
